application: eric-guo-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "15m"

handlers:
# index files
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)/index.html

# site root
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /404.html
  static_files: public/404.html
  upload: public/404.html

- url: /archives
  static_files: public/archives/index.html
  upload: public/archives/index.html

- url: /about
  static_files: public/about/index.html
  upload: public/about/index.html

- url: /resume
  static_files: public/resume/index.html
  upload: public/resume/index.html

- url: /categories
  static_files: public/categories/index.html
  upload: public/categories/index.html

# categories have no '/', so can not cover by index files rule
- url: /categories/(.*)
  static_files: public/categories/\1/index.html
  upload: public/categories/(.*)/index.html

- url: /google9328e371a3c890e0\.html
  static_files: public/google9328e371a3c890e0.html
  upload: public/google9328e371a3c890e0.html

- url: /BingSiteAuth\.xml
  static_files: public/BingSiteAuth.xml
  upload: public/BingSiteAuth.xml

# www.mywot.com for blog.cloud-mes.com
- url: /mywotd928d2c8ae3fd5f09f97\.html
  static_files: public/mywotd928d2c8ae3fd5f09f97.html
  upload: public/mywotd928d2c8ae3fd5f09f97.xml

- url: /
  static_dir: public

error_handlers:
- file: 404.html
